# Generated by Django 5.0.4 on 2024-04-19 18:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_name', models.CharField(max_length=200, verbose_name='Название технического обслуживания')),
                ('maintenance_mileage', models.IntegerField(default=0, max_length=7, verbose_name='Рекомендованная периодичность (пробег)')),
            ],
            options={
                'verbose_name': 'Вид технического обслуживания',
                'verbose_name_plural': 'Виды технического обслуживания',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(default='User', max_length=200, verbose_name='Роль пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='car_img/', verbose_name='Изображение')),
                ('car_name', models.CharField(max_length=100, verbose_name='Название')),
                ('car_color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('car_mileage', models.IntegerField(default=0, max_length=7, verbose_name='Текущий пробег')),
                ('car_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='RecordMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_maintenance_date', models.DateField(verbose_name='Дата технического обслуживания')),
                ('record_car_mileage', models.IntegerField(default=0, max_length=7, verbose_name='Пробег автомобиля на данный момент')),
                ('record_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('record_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record_maintenance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typemaintenance')),
            ],
            options={
                'verbose_name': 'Запись технического обслуживания',
                'verbose_name_plural': 'Записи технического обслуживания',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_mileage', models.IntegerField(default=0, max_length=7, verbose_name='Пробег проведения тех. обслуживания')),
                ('record_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('maintenance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typemaintenance')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
